#!/usr/bin/env bash
set -euo pipefail
required=(
  "pyproject.toml"
  "src/game_engine/runtime/contracts.py"
  "src/game_engine/runtime/engine.py"
  "src/game_engine/runtime/scene_store.py"
  "src/game_engine/runtime/renderer.py"
  "src/game_engine/runtime/render_backends.py"
  "src/game_engine/runtime/ecs.py"
  "src/game_engine/runtime/physics.py"
  "src/game_engine/runtime/audio.py"
  "src/game_engine/runtime/ui.py"
  "src/game_engine/runtime/animation.py"
  "src/game_engine/runtime/gameplay.py"
  "src/game_engine/runtime/scheduler.py"
  "src/game_engine/runtime/resources.py"
  "src/game_engine/editor/scene_io.py"
  "src/game_engine/editor/import_service.py"
  "src/game_engine/pipeline/importer.py"
  "src/game_engine/pipeline/manifest_builder.py"
  "src/game_engine/pipeline/bundler.py"
  "src/game_engine/pipeline/cook.py"
  "src/game_engine/services/validators.py"
  "src/game_engine/services/multiplayer_server.py"
  "src/game_engine/ecosystem/validators.py"
  "src/game_engine/ops/release_ops.py"
  "src/game_engine/core/config.py"
  "src/game_engine/core/events.py"
  "src/game_engine/core/jobs.py"
  "src/game_engine/pipeline/verify.py"
  "src/game_engine/project/workflow.py"
  "src/game_engine/perf/benchmark.py"
  "benchmarks/thresholds.json"
  "scripts/benchmark.sh"
  "tests/test_runtime_mvp.py"
  "tests/test_pipeline_flow.py"
  "tests/test_runtime_systems.py"
  "tests/test_multiplayer_service.py"
  "tests/test_project_workflow.py"
  "tests/test_gameplay_upgrade.py"
  "tests/test_runtime_scheduler_resources.py"
  "tests/test_core_and_pipeline_verify.py"
  "tests/test_benchmark_plan.py"
)
for p in "${required[@]}"; do
  [[ -f "$p" ]] || { echo "Missing: $p"; exit 1; }
done
echo "Structure check passed"
